apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YXBpdXNlcg==                # base64加密 apiuser
  userpwd: MTIzNHNtYWxsQklH        # base64加密 1234smallBIG
  adminname: cm9vdA==
  adminpwd: MTIzNHNtYWxsQklH 